var parking_locations = {
	"parking": [
		{"top_left": [361, 62], "bottom_right": [386, 122], "pid": "13rfae",
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [384, 71], "bottom_right": [411, 77], "pid": "avfafef",
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [353, 118], "bottom_right": [362, 138],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [253, 253], "bottom_right": [273, 279],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [236, 269], "bottom_right": [250, 278],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [244, 261], "bottom_right": [250, 270],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [240, 316], "bottom_right": [250, 324],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [144, 614], "bottom_right": [184, 621],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [232, 342], "bottom_right": [257, 661],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [271, 568], "bottom_right": [304, 574],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [271, 576], "bottom_right": [298, 585],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [379, 640], "bottom_right": [438, 649],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [395, 725], "bottom_right": [431, 734],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [444, 586], "bottom_right": [468, 591],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [515, 608], "bottom_right": [523, 628],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [521, 624], "bottom_right": [532, 629],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [511, 515], "bottom_right": [544, 529],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [444, 586], "bottom_right": [468, 591],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [558, 464], "bottom_right": [567, 483],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [546, 414], "bottom_right": [553, 420],
		"parkingPasses": "A, B, C", "timeRestrictions": "XX:XX a.m.-YY:YYp.m."},
		{"top_left": [316, 154], "bottom_right": [321, 170],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [384, 90], "bottom_right": [393, 110],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [427, 120], "bottom_right": [440, 157],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [252, 279], "bottom_right": [274, 289],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [265, 291], "bottom_right": [273, 299],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [321, 202], "bottom_right": [341, 208],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [334, 209], "bottom_right": [341, 219],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [357, 206], "bottom_right": [366, 209],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [373, 201], "bottom_right": [386, 206],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [335, 275], "bottom_right": [341, 292],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [198, 373], "bottom_right": [218, 396],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [197, 402], "bottom_right": [208, 420],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [248, 374], "bottom_right": [265, 386],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [266, 355], "bottom_right": [271, 404],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [275, 396], "bottom_right": [293, 403],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [276, 355], "bottom_right": [281, 366],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [293, 356], "bottom_right": [299, 366],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [311, 359], "bottom_right": [325, 371],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [309, 388], "bottom_right": [316, 401],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [40, 440], "bottom_right": [50, 465],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [182, 474], "bottom_right": [198, 484],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [264, 442], "bottom_right": [276, 449],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [357, 333], "bottom_right": [364, 346],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [266, 499], "bottom_right": [280, 503],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [278, 550], "bottom_right": [306, 560],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [318, 546], "bottom_right": [340, 555],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [126, 632], "bottom_right": [155, 636],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [170, 633], "bottom_right": [193, 637],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [347, 636], "bottom_right": [377, 651],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [346, 657], "bottom_right": [372, 685],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [377, 659], "bottom_right": [385, 675],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [396, 657], "bottom_right": [414, 661],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [426, 556], "bottom_right": [435, 584],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [397, 706], "bottom_right": [405, 724],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [422, 540], "bottom_right": [429, 544],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [480, 492], "bottom_right": [506, 500],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [485, 563], "bottom_right": [506, 576],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [522, 567], "bottom_right": [539, 575],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [498, 582], "bottom_right": [508, 594],
		"parkingPasses": "A, B", "timeRestrictions": "RR:RR a.m.-SS:SSp.m."},
		{"top_left": [355, 194], "bottom_right": [364, 203],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [444, 226], "bottom_right": [448, 234],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [271, 300], "bottom_right": [274, 312],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [407, 312], "bottom_right": [417, 328],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [420, 304], "bottom_right": [443, 324],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [436, 326], "bottom_right": [446, 355],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [398, 359], "bottom_right": [416, 382],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [270, 442], "bottom_right": [291, 451],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [361, 444], "bottom_right": [364, 533],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [342, 459], "bottom_right": [359, 467],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [338, 469], "bottom_right": [348, 479],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [363, 499], "bottom_right": [386, 504],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [400, 462], "bottom_right": [424, 473],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [431, 441], "bottom_right": [434, 529],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [439, 518], "bottom_right": [448, 530],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [435, 482], "bottom_right": [460, 485],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [435, 490], "bottom_right": [474, 494],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [482, 462], "bottom_right": [504, 467],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [437, 546], "bottom_right": [447, 556],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [476, 544], "bottom_right": [488, 561],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [510, 579], "bottom_right": [526, 602],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [493, 594], "bottom_right": [503, 602],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [529, 507], "bottom_right": [543, 513],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [276, 528], "bottom_right": [306, 547],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [282, 495], "bottom_right": [286, 514],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."},
		{"top_left": [209, 471], "bottom_right": [245, 494],
		"parkingPasses": "A", "timeRestrictions": "PP:PP a.m.-QQ:QQp.m."}
	]
}

module.exports = parking_locations; 